services:
  postgres-prothSync:
    image: 'postgres:18'
    container_name: postgres-prothSync
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
    volumes:
      - prothSync_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - db-net

  redis-prothSync:
    image: 'redis:7-alpine'
    container_name: redis-prothSync
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      TZ: ${TZ}
    ports:
      - "6379:6379"
    networks:
      - db-net
    volumes:
      - prothSync_redis_data:/data

networks:
  db-net:
    name: db-net

volumes:
  prothSync_postgres_data:
  prothSync_redis_data: